PalletTown_Text_OakThanksPidgey::
    .string "OAK: Well, my good PIDGEY,\n"
    .string "thank you for the help.\p"
    .string "I think I understand your\n"
    .string "habitat a little better now.$"
    
PalletTown_Text_OakIsGettingOld::
    .string "It's a shame…\p"
    .string "I'm getting too old to go out\n"
    .string "as long as I used to.\p"
    .string "I wonder if any of my old\n"
    .string "friends feel this way…$"

PalletTown_Text_OakSaysGoodbyeToPidgey::
    .string "Haha! Oh, don't worry about me!\p"
    .string "I've had plenty of adventures of my\n"
    .string "own over all these years!\p"
    .string "Fly along now, little one.$"

PalletTown_Text_OakSeesPlayer::
    .string "{PLAYER}?!$"

PalletTown_Text_OakGetsAttacked::
    .string "Hey! Wait!\n"
    .string "Don't come closer!\p"
    .string "What's gotten into you?\p"
    .string "It's unsafe! Wild POKéMON\n"
    .string "live in the tall grass!\p"
    .string "Hmm? Wh-what's that?!$"

PalletTown_Text_OakPostCatch::
    .string "My, my…\p"
    .string "I surely wouldn't have expected a\n"
    .string "PIKACHU to appear around here!\p"
    .string "…What's that? You saw this PIKACHU\n"
    .string "outside your house last night?\p"
    .string "Curiouser and curiouser…\p"
    .string "Oh, of course! I promised to give\n"
    .string "you your POKéMON today!\p"
    .string "Here, come with me!$"

PalletTown_Text_OakDontGoOut::
    .string "OAK: Hey! Wait!\n"
    .string "Don't go out!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "OAK: It's unsafe!\n"
    .string "Wild POKéMON live in tall grass!\p"
    .string "You need your own POKéMON for\n"
    .string "your protection.\p"
    .string "I know!\n"
    .string "Here, come with me!$"

PalletTown_Text_RaisingMonsToo::
    .string "I'm raising POKéMON, too.\p"
    .string "When they get strong, they can\n"
    .string "protect me.$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "Technology is incredible!\p"
    .string "You can now store and recall items\n"
    .string "and POKéMON as data via PC.$"

PalletTown_Text_OakPokemonResearchLab::
    .string "OAK POKéMON RESEARCH LAB$"

PalletTown_Text_PlayersHouse::
    .string "{PLAYER}'s house$"

PalletTown_Text_RivalsHouse::
    .string "{RIVAL}'s house$"

PalletTown_Text_TownSign::
    .string "PALLET TOWN\n"
    .string "Shades of your journey await!$"

PalletTown_Text_OakLetMeSeePokedex::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "You're back, are you?\p"
    .string "How much have you filled in your\n"
    .string "POKéDEX?\p"
    .string "May I see it?\p"
    .string "Let's see…$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "You've caught {STR_VAR_2}…\p"
    .string "Hm, it looks as if you're putting\n"
    .string "in an honest effort.\p"
    .string "When you manage to fill it some\n"
    .string "more, come show me, please.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "You've caught… {STR_VAR_2}!?\n"
    .string "Now, this is impressive!\p"
    .string "There's something I wanted to ask\n"
    .string "of you, {PLAYER}.\p"
    .string "Come.\n"
    .string "Follow me.$"

PalletTown_Text_OakYouEnjoyingTraveling::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "You seem to be enjoying traveling.\p"
    .string "Knowing you, {PLAYER}, I can easily\n"
    .string "imagine you going out to even more\l"
    .string "exotic locales.\p"
    .string "Good for you, good for you.\n"
    .string "Hohoho.$"

